-- WAITLIST_EMAILS TABLE
CREATE TABLE public.waitlist_emails (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL UNIQUE,
  created_at timestamptz DEFAULT now()
);

-- RLS Policies for waitlist_emails
ALTER TABLE public.waitlist_emails ENABLE ROW LEVEL SECURITY;

-- Allow anyone to insert emails into waitlist (no auth required)
CREATE POLICY "Anyone can join the waitlist" ON public.waitlist_emails 
FOR INSERT 
WITH CHECK (true);

-- Only authenticated users can view waitlist (for admin purposes)
CREATE POLICY "Only authenticated users can view waitlist" ON public.waitlist_emails 
FOR SELECT 
USING (auth.role() = 'authenticated');